### ISSUE TITLE
Stop duplicating patch API code

### ISSUE THREAD

**Issue by nt1m** [JanitorTechnology/janitor#109]
Atm, we duplicate 4x a bunch of code used for validating JSON patch.

**Comment by jankeromnes** [comment]
For such a small, re-usable snippet, I think it's better to simply duplicate it a few times than to create a weird module that makes our dependency graph more complex.

As Sandi Metz puts it, we should [prefer duplication over the wrong abstraction](https://www.sandimetz.com/blog/2016/1/20/the-wrong-abstraction) (have a look at her article, it's an eye-opening and inspiring read).

**Comment by nt1m** [comment]
It's easy to forget some parts of the validation. Something like requireNonNull in java which is a function which throws if the argument is null.

**Comment by jankeromnes** [comment]
If we go with a simple:

```js
try {
  const operations = JSON.parse(json);
  jsonpatch.applyPatch(object, operations, true);
} catch (error) {
  log('[fail] jsonpatch', error);
  response.statusCode = 400; // Bad Request
  response.json({ error: 'Invalid JSON Patch' }, null, 2);
  return;
}

db.save();
response.json(object, null, 2);
```

I'd be ok for duplicating it across the codebase. Not much opportunity for missing parts of it if you copy/paste the block. Also, reviewers should hopefully catch missing validations.

And I think having a "utils" module that grows indefinitely with [accidental complexity](https://www.quora.com/What-are-essential-and-accidental-complexity) is much more costly than any small validation errors we might miss.

**Comment by nt1m** [comment]
Actually, I agree with you, because the configuration API has some extra code for validation.
