### ISSUE TITLE
Auto blurring textbox and input makes keyboard warriors life difficult

### ISSUE THREAD

**Issue by arshdkhn1** [JanitorTechnology/janitor#137]
Hi, textbox and input automatically get blur event after validating the text entered by the user.  If the user tries to copy all the text or paste new text then instead of copy/pasting the desired content whole body element is selected. Check out this video - https://youtu.be/m5nuDth46sA

**Comment by jankeromnes** [comment]
Whoops, that's a recent regression and it's my fault: 50a470de401926c3557a029298305caac371ac4d

I don't remember why we decided to `blur()` elements in the first place. Maybe we shouldn't!

**Comment by jankeromnes** [comment]
Hm, actually, the SSH public key textarea can only be validated when the element is blurred (that's the submit trigger). I can fix the auto-blurring for all the other inputs (which can be validated with `Enter`), but SSH box will still have to be blurred by the user.
