### ISSUE TITLE
Install valgrind in containers.

### ISSUE THREAD

**Issue by nbp** [JanitorTechnology/janitor#143]
Adding --enable-valgrind to the mozconfig of firefox cause a build failure because valgrind headers are not available.

**Comment by jankeromnes** [comment]
Thanks a lot for opening this issue! @nt1m could you please install the latest stable valgrind in our ubuntu-dev base Dockerfile? Thanks!

**Comment by jankeromnes** [comment]
Actually, that might not be enough to add the necessary headers. @nbp could you please paste the build error log you get? Do you happen to know how we can install the necessary valgrind headers on Ubuntu 16.04?

@nt1m if you try to fix this, please first try to reproduce the build issue in a firefox container, un order to identify exactly which commands are required to fix the problem @nbp is facing.

**Comment by nt1m** [comment]
https://github.com/JanitorTechnology/dockerfiles/pull/81

**Comment by jankeromnes** [comment]
I confirm that `apt-get install valgrind` fixes this issue!

Tim's pull request was merged, and new project images including the fix are being built now on CircleCI, and will be deployed on Janitor over the coming days.
