### ISSUE TITLE
No feedback while deleting containers and delete requests gets 404 response

### ISSUE THREAD

**Issue by arshdkhn1** [JanitorTechnology/janitor#144]
I was trying to delete containers and it was really a bad experience deleting them. There wasn't any page reload and feedback, all I had to do was to reload page manually in order to see that containers were deleted or not.

**Comment by arshdkhn1** [comment]
this issue was only present in containers that have `start failed` tag

**Comment by jankeromnes** [comment]
Thanks a lot for reporting this issue!

@nt1m could you please fix the success/failure feedback with container deletions? Previously we called `alert` with any error message we received, which wasn't ideal but at least it was informative. Now it seems we don't give users any clue to what the problem might be.

**Comment by nt1m** [comment]
@jankeromnes Thanks for finishing this! Sorry I couldn't get to finishing it myself :(

**Comment by jankeromnes** [comment]
No worries! I was happy to address my super tiny nits :) thanks for the fix!
