### ISSUE TITLE
Clicking on "rename a container" should focus on the text field

### ISSUE THREAD

**Issue by bnjbvr** [JanitorTechnology/janitor#167]
STR
===

- go to my contributions
- click "rename" icon next to a contribution's name

Observed
===

The contribution's name is replaced by a text field, but focus stays outside. This means that pressing Enter or clicking anywhere outside the field doesn't blur the input, and thus doesn't show the name back. Which looks a bit odd to me :)

Expected
===

Right after clicking, the browser focuses in the text field. It might even select all the text inside the text field, so it's easy and quick to replace it entirely.

**Comment by arshdkhn1** [comment]
Is this bug still there? I was not able to reproduce it on my pc.

**Comment by bnjbvr** [comment]
Yes, I just repro'd it.

**Comment by jankeromnes** [comment]
@arshdkhn1 In https://janitor.technology/containers/, when you click on the Pencil icon, the input field that appears is not automatically focused (you can't just click on the Pencil and type away, you need to click again into the input field to focus it).

**Comment by jankeromnes** [comment]
Thanks a lot to @bnjbvr for the great suggestion and @nt1m for the quick fix!
