### ISSUE TITLE
Project Descriptions

### ISSUE THREAD

**Issue by Tribex** [JanitorTechnology/janitor#17]
A quick description on the projects page for each project and what's included in it would be useful to those preparing to set up a contribution.
Particularly the KDE project could use this, as it's very unclear what components of the KDE project are included.

A link to the version control or primary documentation resource of each project wouldn't hurt either.

**Comment by jankeromnes** [comment]
Great idea, thank you @Tribex! Will post back here when project descriptions are being added.

**Comment by jankeromnes** [comment]
Note: There is now a `description` field in every project's `janitor.json` [configuration file](https://github.com/JanitorTechnology/dockerfiles/commit/b3cf363401454306e61d5e8f46170eaa2967ff6d). We can fix this issue by simply displaying these descriptions on the website.
