### ISSUE TITLE
Put a white "halo" around the favicon

### ISSUE THREAD

**Issue by notriddle** [JanitorTechnology/janitor#187]
![I can't see the black favicon against the dark-color inactive Firefox tabs](https://user-images.githubusercontent.com/1593513/32517775-aae3a7da-c3c4-11e7-831f-868039dfabc6.PNG)

**Comment by Coder206** [comment]
What are your thoughts on something like this: 
![janitor_bk](https://user-images.githubusercontent.com/7758155/34279442-ddf5ee58-e67e-11e7-8775-acb40e96980d.png)

**Comment by nt1m** [comment]
I would just prefer putting the Janitor icon inside a white square or white circle rather than adding a white shadow.

**Comment by notriddle** [comment]
Developer edition, though I think Nightly's the same.

**Comment by arshdkhn1** [comment]
@notriddle putting halo around the logo will make the actual logo a bit small.. any other suggestions to tackle this issue..

**Comment by arshdkhn1** [comment]
@notriddle what do you about this - https://codepen.io/arshdkhn1/full/WddgJe/ ?

**Comment by notriddle** [comment]
The problem is that the new design uses a black Sweepy, so I'm not sure having a white Sweepy in the favicon would make sense.

**Comment by nt1m** [comment]
@arshdkhn1 I like it!

**Comment by arshdkhn1** [comment]
@notriddle I dont understand what do you mean by `black Sweepy` ? :sweat_smile:

**Comment by arshdkhn1** [comment]
@Coder206  @nt1m @jankeromnes @notriddle check the [link](https://codepen.io/arshdkhn1/pen/WddgJe) again, I have added some possible backgrounds of browser tabs.. I think it looks good.

**Comment by notriddle** [comment]
I'm comparing the logo on https://janitor.technology and https://janitor.technology/design/

**Comment by notriddle** [comment]
But, anyway, putting a black box around it wouldn't be too bad.

**Comment by arshdkhn1** [comment]
@notriddle oh, now i get you. yes, your comment make sense..
