### ISSUE TITLE
Allow editing project descriptions

### ISSUE THREAD

**Issue by jankeromnes** [JanitorTechnology/janitor#202]
@aminemboulouma recently added project descriptions in our object model and HTML templates (see c770ff9ecc700b5f3d3876a87bb40952d4abadbb and 6a184f2ced5adff15c75420246244e6bc6d60592). (Thanks a lot!)

But for now, these descriptions can only be edited by manually tweaking `db.json` while the server is offline.

It would be great to add a way for project admins to edit their project's description, e.g. by adding a new form to the [project admin page](https://github.com/JanitorTechnology/janitor/blob/6a184f2ced5adff15c75420246244e6bc6d60592/templates/admin-projects.html#L41-L45).

Bonus points: This can be done easily by simply adding an older `projectdb` form to the project admin page template, but a better way to fix this would be to add a new API handler to [/api/projects-api.js](https://github.com/JanitorTechnology/janitor/blob/api/projects-api.js), similar to the [handler to edit users with JSON Patch](https://github.com/JanitorTechnology/janitor/blob/6a184f2ced5adff15c75420246244e6bc6d60592/api/user-api.js#L45-L87), and then use that API from the admin page with a more recent fetch form like [this one](https://github.com/JanitorTechnology/janitor/blob/6a184f2ced5adff15c75420246244e6bc6d60592/templates/settings-account.html#L8-L11).

**Comment by nt1m** [comment]
Fixed by #285
