### ISSUE TITLE
default gitconfig

### ISSUE THREAD

**Issue by julienw** [JanitorTechnology/janitor#212]
Here are some more suggestions for the default gitconfig:

```
[help]
  autocorrect = 1
[diff]
  context = 8
```

* autocorrect automatically replaces command names: like chekcout gets replaced by checkout automatically.
* context of 8 lines is Mozilla's recommendation

**Comment by jankeromnes** [comment]
Great suggestions, thanks a lot! :smile: we should add them to our template file.
