### ISSUE TITLE
Can't delete old irill.janitor.tech containers

### ISSUE THREAD

**Issue by nt1m** [JanitorTechnology/janitor#313]

**Comment by nt1m** [comment]
I managed to delete the moz1 containers, it just took a crazy long time to delete

**Comment by jankeromnes** [comment]
Same error as #293. IRILL is down, so any `docker rm $container` calls will time out.

To fix this once and for all, we should make container deletion "asynchronous", i.e. when a user "Delete"s a container, Janitor should immediately confirm the deletion, and mark the container as "to be deleted". Then, it can issue a `docker rm` call in the background, without the user needing to wait for that to finish, and if there are errors during the delete, Janitor can log that error server-side and/or retry later.

**Comment by jankeromnes** [comment]
Fixed by 6c5567cc88e0bbdfae5008ffb7f033f71a905caa.
