### ISSUE TITLE
servo container hasn't been built for two months

### ISSUE THREAD

**Issue by jdm** [JanitorTechnology/janitor#345]
Is that a bad thing?

**Comment by nt1m** [comment]
The servo docker image fails to build:

https://gist.github.com/nt1m/fd59c8ea593e41ecb6a6c142e4222004

If you can help us shed a light on the failure, we'd appreciate that :)

**Comment by jdm** [comment]
That looks like https://github.com/servo/servo/issues/20712. What if you set the environment variable described there?
