### ISSUE TITLE
Update README Sponsorship

### ISSUE THREAD

**Issue by Coder206** [JanitorTechnology/janitor#366]
Add the following to the sponsorship section of the README:

- [x] DataDog
- [ ] OVH (potentially)

**Comment by Coder206** [comment]
@jankeromnes Does OVH sponsor OVH1? If so, should we add them to the list of sponsors, else, let's close this for now.

**Comment by jankeromnes** [comment]
@Coder206 No, unfortunately OVH wasn't able to sponsor OVH1 (which I still pay for myself). They did offer us credits for their Public Cloud service, but we currently need dedicated hardware instead of temporary cloud instances (and would need a significant refactor to support cloud instances).

**Comment by jankeromnes** [comment]
So, closing for now. Thanks!
