### ISSUE TITLE
Firefox containers should have moz-phab installed

### ISSUE THREAD

**Issue by rugk** [JanitorTechnology/janitor#422]
When you, as a contributor, want to [submit a patch](https://wiki.mozilla.org/WebExtensions/Contribution_Onramp#Submitting_a_Patch) you get [here](https://moz-conduit.readthedocs.io/en/latest/phabricator-user.html) explaining you should use a tool called `moz-phab`.

When you enter that into the console (at least in the Firefox git version), you get an error and you are totally disappointed that this tool is not pre-installed… :wink:

**Comment by jankeromnes** [comment]
I agree, `moz-phab` is the official tool that the Firefox contribution docs mention.

We already install it in the [Firefox (hg)](https://github.com/JanitorTechnology/dockerfiles/blob/58e2300fd137a157b6c429a9190ea77ddd8ebfda/firefox/firefox-hg.dockerfile#L23-L26) Dockerfile.

The reason we didn't install it in the `Firefox (git)` image was that it didn't support Git back then (and now it doesn't support pure Git, but it requires a `git-cinnabar` checkout).

For Git repositories, `phlay` works quite well. However, if you do prefer to use `moz-phab` (and potentially `git-cinnabar` as well), please make a pull request to our [Firefox (git)](https://github.com/JanitorTechnology/dockerfiles/blob/master/firefox/firefox-git.dockerfile) Dockerfile and simply copy-paste the `moz-phab` installation instructions used in `Firefox (hg)`.

Thanks! 😄

**Comment by rugk** [comment]
As I have no way to test these changes, I'd rather leave this as a suggestion for you to implement. :smiley:

**Comment by jankeromnes** [comment]
@rugk the Dockerfiles are built automatically by CircleCI once you open a Pull Request, so it will be tested automatically :blush: and it's really just a simple copy-and-paste. But no pressure, if you don't want to do it, I'll try to do it soon (please ping me if I forget).

**Comment by jankeromnes** [comment]
Fixed! 😄 The new images should be built and deployed over the next 24h. After that, new `Firefox (git)` containers should have `moz-phab` pre-installed. Thanks for reporting this issue!
