### ISSUE TITLE
Building ubuntu-dev container from bd59002ab8052e4fff28197ff6af53a761fe98b1 fails

### ISSUE THREAD

**Issue by olberger** [JanitorTechnology/janitor#431]
After git submodules init && git submodules update, I tried rebuilding the ubuntu-dev container, and got:
```
  Installing /home/user/.cargo/bin/rg
    Updating git repository `https://github.com/rust-lang-nursery/rust-clippy.git`
  Installing clippy v0.0.212 (https://github.com/rust-lang-nursery/rust-clippy.git#e176324f)
error: binary `cargo-clippy` already exists in destination
Add --force to overwrite
The command '/bin/sh -c cargo install fd-find  && cargo install ripgrep  && cargo +nightly install clippy --git https://github.com/rust-lang-nursery/rust-clippy.git' returned a non-zero code: 101
```
Hopefuly, this is fixed in later revisions of the dockerfiles, hence the need to update the reference to the valid revision of the submodule ?

Hope this helps,

**Comment by jankeromnes** [comment]
Thanks a lot for reporting this issue! I think it should live under https://github.com/JanitorTechnology/dockerfiles/issues/ instead.

Unfortunately, build problems like these with `clippy` do happen relatively often. Usually, I just wait for them to resolve themselves, but from time to time the install procedures of these Rust components change, so we occasionally need to update our Dockerfiles.

I'll re-trigger a Circle CI build of all our Dockerfiles, to see if we can reproduce this bug.

**Comment by jankeromnes** [comment]
Ah, sorry, I misread your comment about the submodule.

It's indeed likely that our submodule is out-of-date. I'll try to update it as well. (I really hope @renovatebot will do that for us one day.)

**Comment by jankeromnes** [comment]
Hm, I re-triggered a rebuild of all Janitor Dockerfiles yesterday, and `ubuntu-dev` seemed to install `cargo-clippy` just fine, but then it failed during Theia install: https://github.com/JanitorTechnology/dockerfiles/issues/224

So I re-retriggered it, but then it failed again with a different error (`nasm` install):

```
Step 27/53 : RUN __NASM_VERSION__="2.14.02"  && mkdir /tmp/nasm  && cd /tmp/nasm  && wget -qOnasm.tar.xz https://www.nasm.us/pub/nasm/releasebuilds/${__NASM_VERSION__}/nasm-${__NASM_VERSION__}.tar.xz  && tar xf nasm.tar.xz  && cd nasm-${__NASM_VERSION__}/  && ./configure  && make  && sudo make install  && sudo rm -rf /tmp/nasm
 ---> Running in 1342368bc9a7
The command '/bin/sh -c __NASM_VERSION__="2.14.02"  && mkdir /tmp/nasm  && cd /tmp/nasm  && wget -qOnasm.tar.xz https://www.nasm.us/pub/nasm/releasebuilds/${__NASM_VERSION__}/nasm-${__NASM_VERSION__}.tar.xz  && tar xf nasm.tar.xz  && cd nasm-${__NASM_VERSION__}/  && ./configure  && make  && sudo make install  && sudo rm -rf /tmp/nasm' returned a non-zero code: 4
Exited with code 4
```

This error output isn't exactly helpful.

It feels a little like playing roulette, but I'll continue re-triggering and investigating. 🤞

**Comment by jankeromnes** [comment]
Wow, https://www.nasm.us/ is actually down. 😧

**Comment by jankeromnes** [comment]
https://www.nasm.us/ is back up, and the build seems fixed again. 😄 

<img width="459" alt="screenshot 2019-02-18 at 11 24 04" src="https://user-images.githubusercontent.com/599268/52944479-c4580500-336f-11e9-84e7-d7ec8800b997.png">
