### ISSUE TITLE
VM for servo is too small to compile servo

### ISSUE THREAD

**Issue by robert-snakard** [JanitorTechnology/janitor#444]
```
LLVM ERROR: IO failure on output stream: No space left on device
error: Could not compile `script`.
```

**Comment by Coder206** [comment]
Hello @robert-snakard,

Thank you very much for your patience! I wanted to let you know that I was able to compile servo successfully. 

>     Finished dev [unoptimized + debuginfo] target(s) in 22m 05s
> [Warning] Could not generate notification! Optional Python module 'dbus' is not installed.
> Build Completed in 0:22:06

Please re-open this issue if the issue is ongoing on your end.
