### ISSUE TITLE
Site Down

### ISSUE THREAD

**Issue by WesleyBryie** [JanitorTechnology/janitor#523]
The site [janitor.technology](https://janitor.technology) is down. Is this intentional?

**Comment by PTrottier** [comment]
Unfortunately, yes, here's the post about it:

> Dear Janitor user,
> 
> Thank you so much for joining us on this adventure! Reminder: [janitor.technology](https://janitor.technology/) was an open-source developer service that made it easy to contribute to open-source in a single click, by launching fully pre-compiled dev containers in the cloud in seconds.
> 
> This is our final email, letting you know that the Janitor project is coming to an end. In brief:
> - The [janitor.technology](https://janitor.technology/) service will stop official operations on June 30, 2021
> - All user data will be deleted and most servers shut down during July 2021
> - Please switch to alternatives like [gitpod.io](https://gitpod.io/)
> 
> More context:
> 
> Created in 2013, Janitor showed the world that standardized, containerized dev environments accessible from the web are possible, and indeed make it easier for anyone to contribute to open-source in a single click. It supported 16 flagship open-source projects like Firefox and Chromium, and enabled hundreds of developers to make valuable contributions in a single click.
> 
> This approach that Janitor pioneered has recently been gaining traction, with several exciting new initiatives further developing and refining the concept. Notable examples are [Gitpod.io](https://gitpod.io/) and Microsoft's upcoming GitHub Codespaces. That is exactly why I (Jan Keromnes, the creator of Janitor) have joined Gitpod—to help bring this concept to new levels, at a bigger scale.
> 
> In an effort to help ease your transition, we would like to introduce you to Gitpod:
> 
> Today, Gitpod provides the same service as Janitor (one-click dev environments) and it works with any project hosted on GitLab, GitHub, and Bitbucket. For instance, try opening this Rust example in Gitpod—it just works! https://gitpod.io/#https://github.com/gitpod-io/example-rust-cli
> 
> Gitpod is also:
> - Entirely open-source: https://github.com/gitpod-io/gitpod
> - Free for open-source: https://www.gitpod.io/pricing
> - And we give back to open-source: https://www.gitpod.io/blog/gitpod-open-source-sustainability-fund
> 
> If you'd like to try some of Gitpod's power features, the coupon code JANITOR will give you 30% off any paid plan for 6 months if used before August 30, 2021.
> 
> Thank you all so much for coming along! Warm wishes in the next steps of your dev environment journey.
> 
> ❤️ Team Janitor

**Comment by WesleyBryie** [comment]
Oh! It's sad that it had to go away, but it's cool that he joined Gitpod making it easier for him to continue the idea!
