### ISSUE TITLE
Make hosted services URL discoverable

### ISSUE THREAD

**Issue by bnjbvr** [JanitorTechnology/janitor#53]
When using the Kresus container, for which one can spawn a web service running on port 9876, there's no way to discover that the Docker instance has bound the port 9876, and thus to navigate to the URL in the proxy. As a workaround, one can just click the VNC button and change the port in the URL. But things could be simpler: maybe a section with links/buttons (one for each hosted service), which redirects to the service once clicked?

**Comment by jankeromnes** [comment]
Thanks a lot for filing this suggestion! This is indeed a very important feature that should be available in the web app.

I'll fold this issue into the higher-level issue #59.
