### ISSUE TITLE
Use a random cookie name for Janitor

### ISSUE THREAD

**Issue by magopian** [JanitorTechnology/janitor#93]
At the moment, when you want to contribute to janitor (through janitor), the docker host proxy will get confused, and use the same cookie and thus break the auth. This means that no static file will be served.

The current solution is to edit `lib/sessions.js` to change the cookie name on the following lines:
- https://github.com/JanitorTechnology/janitor/blob/135c06adc3a64fabba84c21eac9b62c76b24a2ec/lib/sessions.js#L49
- https://github.com/JanitorTechnology/janitor/blob/135c06adc3a64fabba84c21eac9b62c76b24a2ec/lib/sessions.js#L65

Doing this will allow you to run the janitor app using `node app` in the container's terminal, and access it on `https://moz1.janitor.technology/<container>/8080/`

If we were to use a random cookie name in those two lines, and store that cookie name in the DB for future uses, that should solve the issue.

**Comment by jankeromnes** [comment]
Thanks a lot for filing this issue! This is indeed an annoying bug that already bit me, @bnjbvr, @Coder206 and @nt1m. The good news is that it should be fairly easy to fix.

I suggest doing something akin to this at the top of `/lib/sessions.js`:

```js
const cookienames = db.get('cookienames');
if (!cookienames.token) {
  crypto.randomBytes(10, (error, buffer) => {
    cookienames.token = buffer.toString('hex');
  });
}
```

and then use `cookienames.token` instead of the hard-coded `'token'` (with a better name instead of "cookienames").

Some more explanations about this problem from IRC:

> 15:50:49 <@janx> magopian: so, janitor web app allows you to create containers for various projects
> 15:51:21 <@janx> magopian: when you create a container for a project, it contacts a docker host using the Docker Remote API in order to create a container for you
> 15:52:51 <@janx> that same host also has a proxy that runs on port 443, allowing you to access various container ports (so, you can make a request to https://moz1.janitor.technology/abcdef123456/8080/, and the host "moz1.janitor.technology" will know that you want to connect to port 8080 of the container "abcdef123456")
> 15:53:49 <@janx> but, in order to verify that you actually own container "abcdef123456", it needs to authenticate you first. This works by making your browser a "token" cookie, and sending you on an OAuth2-roundtrip with host "janitor.technology" (where you are already authenticated)
> 15:54:30 <@janx> once you're back on "moz1.janitor.technology", and the host proxy knows you actually own container "abcdef123456", it pipes your request to port 8080 of that container
> 15:55:01 <@janx> if that container happens to contain a Janitor app, this Janitor app will serve its web content to you
>15:55:46 <magopian> i think I understand now, awesome, thanks for the explanation
> 15:55:58 <@janx> however, the Janitor app also tries to authenticate you, by making your browser remember a cookie called "token" (and since it doesn't recognize the current value, which was set by the host-level proxy for authentication, it overwrites it with its own value)
> 15:56:38 <magopian> and is join.js the code for the proxy?
> 15:57:16 <@janx> and when you've received the Janitor app response (containing index.html, and resetting your "token" cookie), your browser tries to make other requests to the proxy (e.g. /js/janitor.js, /css/janitor.css, etc), but since the proxy doesn't recognize the value of your "token" cookie, it resets it again, and tries to send you on another OAuth2 roundtrip...
> 15:57:25 <@janx> TL;DR you're in trouble :P
> 15:58:36 <@janx> magopian: and yes, join.js is the code for the proxy (it's the script you're supposed to run if you want to add your own server to the Janitor cluster, hence the name "join" (as in, `node join` makes you join the Janitor cluster and does a lot of setup things automatically, and also starts listening to port 443 to act like a proxy for local containers))
